name: C++ Windows-x64 Google Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build 3DRadSpace
    uses: ./.github/workflows/cmake-windows-x64.yml
      
  test:
    runs-on: [windows-latest, x64, gpu, self-hosted]
    needs: build
    steps:
    - name: Copy Asset folders
      shell: cmd
      working-directory: ${{ github.workspace }}
      run: xcopy 3DRadSpace\Data\ build\Release\Data\ /s /e /h /y
    - name: Run tests
      shell: cmd
      working-directory: ${{ github.workspace }}\build\Release\
      run: 3DRadSpace-tests.exe