name: C++ Win-x64 Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build 3DRadSpace
    uses: ./.github/workflows/cmake-multi-platform.yml
      
  test:
    runs-on: [windows-latest, x64, gpu]
    needs: build
    steps:
    - name: Copy Asset folders
      shell: cmd
      working-directory: ${{ github.workspace }}\3DRadSpace
      run: xcopy Data\ build\x64-Release\Data\ /s /e /h /y
    - name: Run tests
      shell: cmd
      working-directory: ${{ github.workspace }}\3DRadSpace\build\x64-Release\
      run: 3DRadSpace-tests.exe