name: C++ Win-x64 Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    name: Build 3DRadSpace
    uses: ./.github/workflows/cmake-multi-platform.yml
      
  test:
    runs-on: [windows-latest, x64, gpu]
    needs: build
    steps:
    - name: Copy Asset folders
      shell: bash
      working-directory: ${{ github.workspace }}/3DRadSpace
      run: cp -r ${{github.workspace}}/3DRadSpace/Data ${{github.workspace}}/3DRadSpace/build/x64-Release/Data
    - name: Run tests
      shell: bash
      working-directory: ${{ github.workspace }}/3DRadSpace/build/x64-Release/
      run: ./3DRadSpace-tests.exe
