# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: vcpkg Restore

on:
  workflow_call:

jobs:
  restore:
    runs-on: [windows-latest, x64, self-hosted]

    steps:
    - uses: actions/checkout@v4
    
    - name: Export GitHub Actions cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
    
    - name: Clone vcpkg
      run: git clone https://github.com/microsoft/vcpkg

    #- name: vcpkg bootstrap
    #- run .\vcpkg\bootstrap-vcpkg
    
    - name: vcpkg integrate
      run: vcpkg integrate install
    
    - name: Install assimp
      run: vcpkg install assimp:x64-windows-release

    - name: Install DirectXTK
      run: vcpkg install directxtk:x64-windows-release 
      
    - name: Install FreeType
      run: vcpkg install freetype:x64-windows-release 
      
    - name: Install nlohmann-json
      run: vcpkg install nlohmann-json:x64-windows-release

    - name: Install OpenAL
      run: vcpkg install openal-soft:x64-windows-release

    - name: Install PhysX
      run: vcpkg install physx:x64-windows-release

    - name: Install AngelScript
      run: vcpkg install angelscript:x64-windows-release

    - name: Install Google Test
      run: vcpkg install gtest:x64-windows-release
      
    - name: Install LibVorbis 
      run: vcpkg install libvorbis:x64-windows-release
